Feature/notification enhancements
finarkein/fiul pull request #84
Opened 2022-11-17 12:00 UTC by Prathamesh-Mungarwadi

## Description

## Motivation and Context

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [ ] I have added tests to cover my changes.

2022-11-17 21:01 UTC, dheerajkhardwal approved these changes

2022-11-18 07:01 UTC, primarypi requested changes

2022-11-18 07:01 UTC, primarypi commented on fiul-rest/fiul-rest-notification/src/main/java/io/finarkein/fiul/controller/NotificationController.java
> +//                Mono<SignedConsentDTO> signedConsent = consentService
pls remove commented code

2022-11-18 07:01 UTC, primarypi commented on fiul-rest/fiul-rest-notification/src/main/java/io/finarkein/fiul/controller/NotificationController.java
> +                        && consentNotification.getConsentStatusNotification().getConsentStatus().equalsIgnoreCase("ACTIVE")) {
pls use io.finarkein.fiul.consent.ConsentState.name()

2022-11-18 07:01 UTC, primarypi commented on fiul-rest/fiul-rest-notification/src/main/java/io/finarkein/fiul/controller/NotificationController.java
> +                        && !Objects.equals(consentNotification.getConsentStatusNotification().getConsentStatus(), "ACTIVE")) {
pls use io.finarkein.fiul.consent.ConsentState.name()

2022-11-18 07:20 UTC, primarypi approved these changes

2022-11-18 07:21 UTC, merged